### ISSUE TITLE
API return 403 forbidden on AWS lambda

### ISSUE THREAD

**Issue by vmaerten** [conference-hall/conference-hall#612]
### What happened?

Hello!
We have a Lambda function that calls the API to fetch all proposals. It used to work fine, but it’s now returning a 403 Forbidden error. However, the same request still works when I run it from my browser.

Here’s the response from the fetch call:
```plain
{
  status: 403,
  statusText: 'Forbidden',
  headers: Headers {
    date: 'Thu, 13 Nov 2025 10:51:38 GMT',
    'content-type': 'text/html; charset=UTF-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    'accept-ch': 'Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA',
    'cf-mitigated': 'challenge',
    'critical-ch': 'Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA',
    'cross-origin-embedder-policy': 'require-corp',
    'cross-origin-opener-policy': 'same-origin',
    'cross-origin-resource-policy': 'same-origin',
    'origin-agent-cluster': '?1',
    'permissions-policy': 'accelerometer=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
    'referrer-policy': 'same-origin',
    'server-timing': 'chlray;desc="99ddb70a9bb1b12f", cfL4;desc="?proto=TCP&rtt=908&min_rtt=901&rtt_var=353&sent=3&recv=5&lost=0&retrans=0&sent_bytes=2860&recv_bytes=736&delivery_rate=3004149&cwnd=251&unsent_bytes=0&cid=57da594cca2c6004&ts=129&x=0"',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
    expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=q4KmGOEciLX2RVhmq%2FDJ639kExk0dcWNI2PQPLDxVW20YFnq%2F2zDx8DtB0W432kuGR0n0DzJCP64f1UcCz0YRz7Wp%2FQ9eCF1Os1eb2KefYD0RK%2BZfQozr6y89KUZYbOoBYb3WDw%3D"}],"group":"cf-nel","max_age":604800}',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    vary: 'Accept-Encoding',
    server: 'cloudflare',
    'cf-ray': '99ddb70a9bb1b12f-DUB',
    'content-encoding': 'br',
    'alt-svc': 'h3=":443"; ma=86400'
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: false,
  redirected: false,
  type: 'basic',
  url: 'https://conference-hall.io/api/v1/event/touraine-tech-2026?key=xxxxxxxxxxxxxxxxxxxxxxxxx'
}
```

And the source code : 
```js
const apiKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
const url = `https://conference-hall.io/api/v1/event/touraine-tech-2026?key=${apiKey}`

function getData() {
    return fetch(url).then(r => console.log(r));
}
```

Thanks a lot for your helps

### Expected Behavior

The API should be callable from any source

### Your environment

We use AWS lambda. Locally in my browser it works fine

**Comment by bpetetot** [comment]
Hi @vmaerten,

`'cf-mitigated': 'challenge'` indicates that Cloudflare's security system is blocking your Lambda function's requests. The requests work from your browser because browsers send proper User-Agent headers and other browser fingerprints, but AWS Lambda doesn't.

I have adjusted the WAF Cloudflare configuration, it should work now.
Can you try again ?

**Comment by vmaerten** [comment]
Thanks for your answer but it still does not work :( 

```txt
Response {
  status: 403,
  statusText: 'Forbidden',
  headers: Headers {
    date: 'Fri, 14 Nov 2025 10:25:04 GMT',
    'content-type': 'text/html; charset=UTF-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    'accept-ch': 'Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA',
    'cf-mitigated': 'challenge',
    'critical-ch': 'Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA',
    'cross-origin-embedder-policy': 'require-corp',
    'cross-origin-opener-policy': 'same-origin',
    'cross-origin-resource-policy': 'same-origin',
    'origin-agent-cluster': '?1',
    'permissions-policy': 'accelerometer=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
    'referrer-policy': 'same-origin',
    'server-timing': 'chlray;desc="99e5cd849c5356d9", cfL4;desc="?proto=TCP&rtt=951&min_rtt=938&rtt_var=361&sent=2&recv=5&lost=0&retrans=0&sent_bytes=234&recv_bytes=1007&delivery_rate=1543710&cwnd=250&unsent_bytes=0&cid=303d4be6e918e9de&ts=49&x=0"',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
    expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=dMialwbqD0VOxxjQNI6a5Ynt324InkExRmnLHZk9mbQjAljB6cUjXGHFJPStRhRpzC4%2BbHAJZPyNgndngh4sEGpqezK%2FHN1%2BiSb795gbvfbLUM1AZihLwOy7DiImyfA8V%2B331%2FQ%3D"}],"group":"cf-nel","max_age":604800}',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    vary: 'Accept-Encoding',
    server: 'cloudflare',
    'cf-ray': '99e5cd849c5356d9-DUB',
    'content-encoding': 'br',
    'alt-svc': 'h3=":443"; ma=86400'
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: false,
  redirected: false,
  type: 'basic',
  url: 'https://conference-hall.io/api/v1/event/touraine-tech-2026?key=xxxxxxxxxxxxxxx'
}
```

I can give you, in DM, a link to trigger the lambda and get the result.

I've found a lot of articles related to this issue: 
- https://community.cloudflare.com/t/aws-lambda-requests-blocked-by-bot-fight-mode/296732
- https://community.cloudflare.com/t/aws-lambda-scripts-requests-are-blocked-by-cloudflare-it-returns-403-when-i-enab/649805/2
- https://community.cloudflare.com/t/bot-fight-mode-blocking-my-api-client/403967

**Comment by bpetetot** [comment]
You can send me the link to trigger the lambda to support@conference-hall.io, it will help a lot.

And thanks for article links.

**Comment by bpetetot** [comment]
@vmaerten You can send me the link to trigger the lambda to [support@conference-hall.io](mailto:support@conference-hall.io) 😊 Thanks

**Comment by vmaerten** [comment]
Hello !
Sorry, I’ve been very busy lately. I’ve sent you the link by email.
Just so you know, since our (Touraine Tech) CFP closed last week, this won’t be an issue for us again until next year, around September 2026.
